source 'https://rubygems.org'

gem 'eventmachine'
gem 'thin'
gem 'redis'
gem 'hiredis'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rake'
gem 'json'
gem 'ruby-ip'
gem 'sequel'
gem 'sequel_pg'
gem 'ruby-enum'
gem 'dotenv'
gem 'sidekiq'
gem 'jwt'
gem 'terminal-table'
gem 'time_difference'
gem 'activesupport', '~> 5.1', '>= 5.1.4'

gem 'themis-finals-checker-result', '~> 1.0.0'
gem 'themis-finals-attack-result', '~> 1.0.0'
