source 'https://rubygems.org'

gem 'eventmachine'
gem 'thin'
gem 'redis'
gem 'hiredis'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rake'
gem 'beaneater'
gem 'json'
gem 'ruby-ip'
gem 'sequel'
gem 'sequel_pg'
gem 'ruby-enum'
gem 'aws-sdk'
gem 'dotenv'
# gem 'themis-finals-checker-result'
# gem 'themis-finals-attack-result'

gem 'themis-finals-checker-result', path: '/var/themis/finals/lib/checker-result-rb'
gem 'themis-finals-attack-result', path: '/var/themis/finals/lib/attack-result-rb'
